version: "3.9"
services:
  sensor-fleet:
    container_name: sensor-fleet
    build: sensor-fleet
    environment: 
      AWS_ACCESS_KEY_ID: some_key_id
      AWS_SECRET_ACCESS_KEY: some_secret

  localstack:
    container_name: "localstack"
    build: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  telemetry-collector:
    container_name: telemetry-collector
    build: telemetry-collector
    environment: 
      QUEUE_RECEIPTS_TO_DELETE_INTERVAL_SEC: 5
      SUBMISSIONS_QUEUE_NAME: submissions
      AWS_REGION: eu-west-1
      AWS_ENDPOINT: http://localstack:4566
      EVENTS_DATA_STREAM_NAME: events
      DATA_STREAM_MAX_BUFFER_SIZE: 5
      DATA_STREAM_FLUSH_INTERVAL_SEC: 5
      AWS_VERSION: latest
      QUEUE_MAX_RECEIPTS_TO_DELETE_AT_ONCE: 10
      AWS_KEY: foo
      AWS_SECRET: bar
      QUEUE_WAIT_TIME_SEC: 3
      QUEUE_MAX_NUMBER_OF_MESSAGE_PER_REQUEST: 10
      QUEUE_VISIBILITY_TIMEOUT_SEC: 10
